// SI Accesorios — data and i18n
// Kits de refacción reales · BYD y Nissan

const DATA = {
  // Configurator models -> each maps to a real kit product
  models: {
    BYD: [
      { id: 'byd-mini-dolphin', name: 'Mini Dolphin', product: 'kit-dolphin', size: '125/80 R16', rim: '16"' },
      { id: 'byd-king', name: 'King', product: 'kit-king', size: '155/80 R17', rim: '17"' },
      { id: 'byd-song-pro', name: 'Song Pro', product: 'kit-songpro', size: '155/90 R17', rim: '17"' },
      { id: 'byd-song-plus', name: 'Song Plus', product: 'kit-songplus', size: '155/90 R17', rim: '17"' },
    ],
    Nissan: [
      { id: 'nissan-kicks', name: 'Kicks e-POWER', product: 'kit-kicks', size: '125/80 R16', rim: '16"' },
      { id: 'nissan-xtrail', name: 'X-Trail e-POWER', product: 'kit-xtrail', size: '155/90 R18', rim: '18"' },
    ],
  },

  // What every kit contains
  kit: [
    { icon: 'wheel',  es: 'Llanta con rin',     en: 'Wheel with rim' },
    { icon: 'jack',   es: 'Gato hidráulico',    en: 'Jack' },
    { icon: 'handle', es: 'Maneral',            en: 'Handle bar' },
    { icon: 'socket', es: 'Dado',               en: 'Socket' },
    { icon: 'wrench', es: 'Llave abatible',     en: 'Folding wrench' },
    { icon: 'case',   es: 'Funda protectora',   en: 'Protective case' },
  ],

  // The 5 real kits
  products: [
    {
      id: 'kit-dolphin', sku: 'SI-KIT-BYD-DOLPHIN',
      brand: 'BYD', modelId: 'byd-mini-dolphin',
      title: 'Kit de refacción · BYD Mini Dolphin',
      size: '125/80 R16', rim: '16"', birlos: 4, speed: 90,
      price: 6950, badge_es: 'Más vendido', badge_en: 'Bestseller',
      img: 'assets/kit-dolphin.png',
    },
    {
      id: 'kit-king', sku: 'SI-KIT-BYD-KING',
      brand: 'BYD', modelId: 'byd-king',
      title: 'Kit de refacción · BYD King',
      size: '155/80 R17', rim: '17"', birlos: 5, speed: 90,
      price: 7950, badge_es: null, badge_en: null,
      img: 'assets/kit-king.png',
    },
    {
      id: 'kit-songpro', sku: 'SI-KIT-BYD-SONGPRO',
      brand: 'BYD', modelId: 'byd-song-pro',
      title: 'Kit de refacción · BYD Song Pro',
      size: '155/90 R17', rim: '17"', birlos: 5, speed: 90,
      price: 7950, badge_es: null, badge_en: null,
      img: 'assets/kit-songpro.png',
    },
    {
      id: 'kit-songplus', sku: 'SI-KIT-BYD-SONGPLUS',
      brand: 'BYD', modelId: 'byd-song-plus',
      title: 'Kit de refacción · BYD Song Plus',
      size: '155/90 R17', rim: '17"', birlos: 5, speed: 90,
      price: 7950, badge_es: null, badge_en: null,
      img: 'assets/kit-songplus.png',
    },
    {
      id: 'kit-kicks', sku: 'SI-KIT-NIS-KICKS',
      brand: 'Nissan', modelId: 'nissan-kicks',
      title: 'Kit de refacción · Nissan Kicks e-POWER',
      size: '125/80 R16', rim: '16"', birlos: 5, speed: 90,
      price: 6950, badge_es: null, badge_en: null,
      img: 'assets/kit-kicks.png',
    },
    {
      id: 'kit-xtrail', sku: 'SI-KIT-NIS-XTRAIL',
      brand: 'Nissan', modelId: 'nissan-xtrail',
      title: 'Kit de refacción · Nissan X-Trail e-POWER',
      size: '155/90 R18', rim: '18"', birlos: 5, speed: 90,
      price: null, badge_es: 'Próximamente', badge_en: 'Coming soon',
      img: 'assets/kit-xtrail.png',
    },
  ],

  blog: [
    {
      id: 'b-01', read: '4 min',
      tag_es: 'Guía', tag_en: 'Guide',
      title_es: 'Cómo elegir el kit de refacción correcto para tu auto',
      title_en: 'How to pick the right spare kit for your car',
      excerpt_es: 'Medida, rin, birlos y por qué importa el ajuste exacto por modelo.',
      excerpt_en: 'Size, rim, lugs and why exact per-model fit matters.',
    },
    {
      id: 'b-02', read: '3 min',
      tag_es: 'Seguridad', tag_en: 'Safety',
      title_es: '¿Por qué la llanta de refacción marca 90 km/h?',
      title_en: 'Why does the spare wheel say 90 km/h?',
      excerpt_es: 'Las llantas de uso temporal tienen límites. Aquí el porqué.',
      excerpt_en: 'Temporary-use spares have limits. Here\u2019s the why.',
    },
    {
      id: 'b-03', read: '5 min',
      tag_es: 'BYD', tag_en: 'BYD',
      title_es: 'BYD eléctricos: qué traer en la cajuela siempre',
      title_en: 'Electric BYD: what to always keep in the trunk',
      excerpt_es: 'Los híbridos y EV salieron de fábrica sin kit. Te decimos qué falta.',
      excerpt_en: 'Hybrids and EVs left the factory with no kit. Here\u2019s what\u2019s missing.',
    },
    {
      id: 'b-04', read: '4 min',
      tag_es: 'Mantenimiento', tag_en: 'Maintenance',
      title_es: 'Cómo usar el gato y el maneral sin dañar el auto',
      title_en: 'Using the jack and handle without damaging the car',
      excerpt_es: 'Puntos de apoyo, torque y los errores más comunes al cambiar una llanta.',
      excerpt_en: 'Jacking points, torque and the most common tire-change mistakes.',
    },
  ],

  t: {
    es: {
      nav: { home: 'Inicio', catalog: 'Catálogo', config: 'Cotizador', blog: 'Blog', contact: 'Contacto', privacy: 'Aviso de Privacidad', terms: 'Términos y Condiciones', legal: 'Legal' },
      hero_eyebrow: 'Kits de refacción · BYD y Nissan',
      hero_title_a: 'La refacción ', hero_title_em: 'completa', hero_title_b: '.', hero_title_c: 'La primera vez.',
      hero_sub: 'No solo la llanta: kit completo con gato, maneral, dado, llave abatible y funda — armado por modelo, con ajuste exacto y entrega en 48 h.',
      cta_catalog: 'Ver kits',
      cta_quote: 'Cotizar por WhatsApp',
      cta_config: 'Cotizar por modelo',
      kit_title: 'Cada kit incluye',
      kit_sub: 'Seis piezas. Todo lo que tu auto necesitaba de fábrica y no traía.',
      models_title: 'Modelos disponibles',
      featured: 'Modelos',
      why: '¿Por qué SI Accesorios?',
      why_items: [
        { t: 'Ajuste exacto por modelo', d: 'Cada kit corresponde a la medida y birlos de tu auto. Sin adivinar.' },
        { t: 'Entrega 48 h CDMX y AMC', d: 'Foráneo por paquetería con guía rastreable.' },
        { t: 'Cotización por WhatsApp', d: 'Mándanos tu modelo y te confirmamos disponibilidad al instante.' },
        { t: 'Kit completo, no piezas sueltas', d: 'Llanta, herramienta y funda en un solo paquete listo para la cajuela.' },
      ],
      includes_label: 'Incluye los 6 componentes',
      contact_title: '¿Listo para cotizar?',
      contact_sub: 'Tres campos. Te respondemos el mismo día hábil.',
      catalog_title: 'Catálogo',
      catalog_h: 'Todos los kits.',
      catalog_sub: 'Filtra por marca y rin. Cada kit trae las 6 piezas.',
      filter_all: 'Todo',
      filter_brand: 'Marca',
      filter_rim: 'Rin',
      filter_clear: 'Limpiar filtros',
      no_results: 'No encontramos coincidencias. Cotiza tu modelo por WhatsApp.',
      product_specs: 'Especificaciones',
      product_includes: 'Qué incluye el kit',
      product_birlos: 'Birlos',
      product_size: 'Medida',
      product_speed: 'Vel. máx.',
      product_quote_price: 'Precio a cotizar',
      product_add: 'Agregar a cotización',
      product_quote: 'Cotizar este kit',
      product_back: '← Volver al catálogo',
      cart_title: 'Tu cotización',
      cart_empty: 'Aún no agregas kits.',
      cart_send: 'Enviar por WhatsApp',
      cart_total: 'Total estimado',
      cart_toquote: 'A cotizar',
      blog_title: 'Notas técnicas',
      blog_h: 'Notas del taller.',
      blog_sub: 'Lo que sí te conviene saber antes de necesitar la refacción.',
      blog_read: 'Leer',
      contact_form: {
        name: 'Nombre', phone: 'Teléfono', model: 'Modelo de tu auto', message: 'Mensaje',
        submit: 'Enviar mensaje', sent: '✓ Mensaje enviado. Te respondemos en máx. 24 h.',
        err_name: 'Falta tu nombre',
        err_phone: 'Teléfono de 10 dígitos',
        err_message: 'Cuéntanos un poco más',
      },
      footer_hours: 'Lun–Vie 10–19 · Sáb 10–14',
      footer_addr: 'CDMX · Envíos a toda la república',
      footer_legal: '© 2026 SI Accesorios · Soluciones Integrales',
      footer_tag: 'Kits de refacción con ajuste exacto para BYD y Nissan.',
      config_title: 'Cotizador por modelo',
      config_step: 'Paso',
      config_of: 'de',
      config_q1: '¿Qué marca?',
      config_q2: '¿Qué modelo?',
      config_q3: 'Tu kit recomendado',
      config_next: 'Continuar',
      config_back: 'Atrás',
      config_send: 'Pedir cotización',
      config_view: 'Ver kit completo',
      config_models: 'modelos',
    },
    en: {
      nav: { home: 'Home', catalog: 'Catalog', config: 'Configurator', blog: 'Notes', contact: 'Contact', privacy: 'Privacy Notice', terms: 'Terms & Conditions', legal: 'Legal' },
      hero_eyebrow: 'Spare kits · BYD and Nissan',
      hero_title_a: 'The ', hero_title_em: 'complete', hero_title_b: ' spare.', hero_title_c: 'First time.',
      hero_sub: 'Not just the wheel: a full kit with jack, handle, socket, folding wrench and case — bundled per model, exact fit, 48 h delivery.',
      cta_catalog: 'View kits',
      cta_quote: 'Quote via WhatsApp',
      cta_config: 'Quote by car model',
      kit_title: 'Every kit includes',
      kit_sub: 'Six pieces. Everything your car needed from the factory and didn\u2019t come with.',
      models_title: 'Available models',
      featured: 'Models',
      why: 'Why SI Accesorios?',
      why_items: [
        { t: 'Exact per-model fit', d: 'Each kit matches your car\u2019s size and lug count. No guessing.' },
        { t: '48 h delivery CDMX & metro', d: 'Anywhere else by tracked courier.' },
        { t: 'WhatsApp quotes', d: 'Send us your model, we confirm availability instantly.' },
        { t: 'Full kit, not loose parts', d: 'Wheel, tools and case in one trunk-ready package.' },
      ],
      includes_label: 'Includes all 6 components',
      contact_title: 'Ready to get a quote?',
      contact_sub: 'Three fields. Reply same business day.',
      catalog_title: 'Catalog',
      catalog_h: 'All kits.',
      catalog_sub: 'Filter by brand and rim. Every kit has the 6 pieces.',
      filter_all: 'All',
      filter_brand: 'Brand',
      filter_rim: 'Rim',
      filter_clear: 'Clear filters',
      no_results: 'No matches. Quote your model via WhatsApp.',
      product_specs: 'Specs',
      product_includes: 'What the kit includes',
      product_birlos: 'Lugs',
      product_size: 'Size',
      product_speed: 'Max speed',
      product_quote_price: 'Quote price',
      product_add: 'Add to quote',
      product_quote: 'Quote this kit',
      product_back: '← Back to catalog',
      cart_title: 'Your quote',
      cart_empty: 'No kits added yet.',
      cart_send: 'Send via WhatsApp',
      cart_total: 'Estimated total',
      cart_toquote: 'To quote',
      blog_title: 'Technical notes',
      blog_h: 'Notes from the shop.',
      blog_sub: 'Useful reading before you need the spare.',
      blog_read: 'Read',
      contact_form: {
        name: 'Name', phone: 'Phone', model: 'Your car model', message: 'Message',
        submit: 'Send message', sent: '✓ Message sent. We reply within 24 h.',
        err_name: 'Your name is missing',
        err_phone: '10-digit phone number',
        err_message: 'Tell us a bit more',
      },
      footer_hours: 'Mon–Fri 10–19 · Sat 10–14',
      footer_addr: 'Mexico City · Shipping nationwide',
      footer_legal: '© 2026 SI Accesorios · Soluciones Integrales',
      footer_tag: 'Spare kits with exact fit for BYD and Nissan.',
      config_title: 'Configurator by model',
      config_step: 'Step',
      config_of: 'of',
      config_q1: 'Which brand?',
      config_q2: 'Which model?',
      config_q3: 'Your recommended kit',
      config_next: 'Continue',
      config_back: 'Back',
      config_send: 'Request quote',
      config_view: 'View full kit',
      config_models: 'models',
    },
  },
};

// ---- Legal pages ----
DATA.legal = {
  privacy: {
    eyebrow_es: 'Legal', eyebrow_en: 'Legal',
    title_es: 'Aviso de Privacidad', title_en: 'Privacy Notice',
    updated_es: 'Última actualización: mayo 2026', updated_en: 'Last updated: May 2026',
    intro_es: 'SI Accesorios (Soluciones Integrales), con domicilio en General Juan Cano #87 Int. 100, Col. San Miguel Chapultepec, Miguel Hidalgo, CDMX, es responsable del tratamiento de sus datos personales conforme a la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP).',
    intro_en: 'SI Accesorios (Soluciones Integrales), located at General Juan Cano #87 Int. 100, Col. San Miguel Chapultepec, Miguel Hidalgo, Mexico City, is responsible for the processing of your personal data under Mexico\u2019s Federal Law on Protection of Personal Data Held by Private Parties (LFPDPPP).',
    sections_es: [
      { h: '1. Datos que recabamos', p: 'Recabamos nombre, teléfono, correo electrónico y modelo de vehículo cuando nos contactas, cotizas un kit o realizas una compra. No recabamos datos personales sensibles.' },
      { h: '2. Finalidades del tratamiento', p: 'Usamos tus datos para: identificar el kit de refacción compatible con tu vehículo, elaborar cotizaciones, procesar pedidos y entregas, dar seguimiento post-venta y atender garantías. Como finalidad secundaria, podemos enviarte información sobre productos y promociones; puedes oponerte a esta en cualquier momento.' },
      { h: '3. Transferencias', p: 'No transferimos tus datos personales a terceros, salvo a las empresas de paquetería necesarias para entregar tu pedido, o cuando lo exija una autoridad competente. En ningún caso comercializamos tu información.' },
      { h: '4. Derechos ARCO', p: 'Tienes derecho a Acceder, Rectificar, Cancelar u Oponerte al tratamiento de tus datos, así como a revocar tu consentimiento. Para ejercerlos, escríbenos a hola@siaccesorios.mx indicando tu nombre completo y la solicitud específica. Responderemos en un máximo de 20 días hábiles.' },
      { h: '5. Uso de cookies', p: 'Nuestro sitio puede usar cookies para mejorar tu experiencia de navegación. Puedes deshabilitarlas desde la configuración de tu navegador sin que esto afecte el acceso al contenido principal.' },
      { h: '6. Cambios al aviso', p: 'Cualquier modificación a este Aviso de Privacidad será publicada en esta misma página. Te recomendamos revisarla periódicamente.' },
    ],
    sections_en: [
      { h: '1. Data we collect', p: 'We collect your name, phone, email and vehicle model when you contact us, request a quote or make a purchase. We do not collect sensitive personal data.' },
      { h: '2. Purpose of processing', p: 'We use your data to: identify the spare kit compatible with your vehicle, prepare quotes, process orders and deliveries, provide post-sale follow-up and handle warranties. As a secondary purpose we may send you product and promotion information; you may opt out at any time.' },
      { h: '3. Transfers', p: 'We do not transfer your personal data to third parties, except to the courier companies required to deliver your order, or when required by a competent authority. We never sell your information.' },
      { h: '4. ARCO rights', p: 'You have the right to Access, Rectify, Cancel or Oppose the processing of your data, and to revoke your consent. To exercise them, email hola@siaccesorios.mx stating your full name and your specific request. We will respond within a maximum of 20 business days.' },
      { h: '5. Use of cookies', p: 'Our site may use cookies to improve your browsing experience. You can disable them in your browser settings without affecting access to the main content.' },
      { h: '6. Changes to this notice', p: 'Any change to this Privacy Notice will be published on this same page. We recommend reviewing it periodically.' },
    ],
  },
  terms: {
    eyebrow_es: 'Legal', eyebrow_en: 'Legal',
    title_es: 'Términos y Condiciones', title_en: 'Terms & Conditions',
    updated_es: 'Última actualización: mayo 2026', updated_en: 'Last updated: May 2026',
    intro_es: 'Estos Términos y Condiciones regulan el uso del sitio de SI Accesorios y la compra de nuestros kits de refacción y accesorios. Al cotizar o comprar, aceptas lo aquí descrito.',
    intro_en: 'These Terms & Conditions govern the use of the SI Accesorios site and the purchase of our spare kits and accessories. By quoting or purchasing, you accept what is described here.',
    sections_es: [
      { h: '1. Productos y compatibilidad', p: 'Cada kit se arma para un modelo específico de vehículo. Es responsabilidad del cliente confirmar el modelo, año y medida antes de la compra. Nuestro equipo te asesora por WhatsApp para asegurar la compatibilidad correcta.' },
      { h: '2. Precios y cotizaciones', p: 'Los precios están expresados en pesos mexicanos (MXN) e incluyen IVA. Las cotizaciones tienen una vigencia de 15 días naturales y están sujetas a disponibilidad de inventario. Los modelos marcados como "Precio a cotizar" se confirman por WhatsApp.' },
      { h: '3. Pagos', p: 'Aceptamos transferencia bancaria, tarjeta y pago contra entrega en zonas seleccionadas. El pedido se procesa una vez confirmado el pago.' },
      { h: '4. Envíos y entregas', p: 'Realizamos entregas en 48 horas dentro de CDMX y zona metropolitana. Para el resto del país, el envío se realiza por paquetería con guía rastreable; los tiempos dependen de la paquetería. Los costos de envío se informan antes de cerrar el pedido.' },
      { h: '5. Garantía y devoluciones', p: 'Nuestros kits cuentan con garantía contra defectos de fabricación. Si recibes un producto incorrecto o con defecto, contáctanos dentro de los 5 días naturales posteriores a la entrega para gestionar el cambio. La llanta es de uso temporal (máx. 90 km/h) y no debe usarse como reemplazo permanente.' },
      { h: '6. Limitación de responsabilidad', p: 'SI Accesorios no se hace responsable por daños derivados del uso incorrecto del producto, instalación inadecuada o por exceder las especificaciones de uso temporal de la llanta de refacción.' },
    ],
    sections_en: [
      { h: '1. Products and compatibility', p: 'Each kit is assembled for a specific vehicle model. It is the customer\u2019s responsibility to confirm the model, year and size before purchase. Our team advises you via WhatsApp to ensure correct compatibility.' },
      { h: '2. Prices and quotes', p: 'Prices are expressed in Mexican pesos (MXN) and include VAT. Quotes are valid for 15 calendar days and subject to inventory availability. Models marked "Quote price" are confirmed via WhatsApp.' },
      { h: '3. Payments', p: 'We accept bank transfer, card and cash on delivery in selected areas. The order is processed once payment is confirmed.' },
      { h: '4. Shipping and delivery', p: 'We deliver within 48 hours in Mexico City and its metro area. For the rest of the country, shipping is done by tracked courier; times depend on the carrier. Shipping costs are reported before closing the order.' },
      { h: '5. Warranty and returns', p: 'Our kits carry a warranty against manufacturing defects. If you receive an incorrect or defective product, contact us within 5 calendar days of delivery to arrange an exchange. The wheel is for temporary use (max 90 km/h) and must not be used as a permanent replacement.' },
      { h: '6. Limitation of liability', p: 'SI Accesorios is not liable for damages arising from incorrect use of the product, improper installation, or exceeding the temporary-use specifications of the spare wheel.' },
    ],
  },
};

window.DATA = DATA;
